export const SIGN_UP = `SIGN_UP`
export const SIGN_UP_SUCCESS = `SIGN_UP_SUCCESS`
export const SIGN_UP_FAILED = `SIGN_UP_FAILED`

export const SIGN_IN = `SIGN_IN`
export const SET_CURRENT_USER = `SET_CURRENT_USER`
export const SIGN_IN_FAILED = `SIGN_IN_FAILED`

export const GET_KITCHENS = `GET_KITCHENS`
export const KITCHENS_RECEIVED = `KITCHENS_RECEIVED`
export const KITCHENS_FAILED = `KITCHENS_FAILED`

export const ADD_KITCHEN = `ADD_KITCHEN`
export const KITCHEN_ADD_SUCCESS = `KITCHEN_ADD_SUCCESS`
export const KITCHEN_ADD_FAILED = `KITCHEN_ADD_FAILED`

export const EDIT_KITCHEN = `EDIT_KITCHEN`
export const KITCHEN_EDIT_SUCCESS = `KITCHEN_EDIT_SUCCESS`
export const KITCHEN_EDIT_FAILED = `KITCHEN_EDIT_FAILED`

export const GET_RESTAURANTS = "GET_RESTAURANTS"
export const RESTAURANTS_RECEIVED= "RESTAURANTS_RECEIVED"
export const RESTAURANTS_FAILED= "RESTAURANTS_FAILED"
export const ADD_RESTAURANT = "ADD_RESTAURANT"
export const RESTAURANT_ADD_SUCCESS = "RESTAURANT_ADD_SUCCESS"
export const RESTAURANT_ADD_FAILED = "RESTAURANT_ADD_FAILED"
export const DELETE_RESTAURANT = "DELETE_RESTAURANT"
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS"